// offscreen -> sandbox

import {
    B2W_RESPONSE_MESSAGE_NAME, type B2WRequestMessage,
    type B2WResponseMessage,
    isB2WRequestMessage,
    W2B_REQUEST_MESSAGE_NAME, type W2BRequestMessage, type W2BResponseMessage
} from "@/utils/messages/worker.ts";
import {isJSCustomStatInternal, type JSCustomStatInternal} from "@/utils/stats/custom_stats";
import Papa from "papaparse";
import type {StatcastRow} from "@/utils/data_types/autogenerated-statcast-row.ts";
import type {SubsidiaryRow} from "@/utils/data_types/subsidiary-row.ts";

//@ts-expect-error unused
async function sendW2BMessage(payload: W2BRequestMessage["payload"]): Promise<W2BResponseMessage> {
    const uuid = crypto.randomUUID();

    parent.postMessage({
        payload,
        message: W2B_REQUEST_MESSAGE_NAME,
        uuid,
    } satisfies W2BRequestMessage, "*");

    return new Promise((resolve, reject) => {
        function handler(event: MessageEvent<any>) {
            if (event.data.uuid === uuid) {
                window.removeEventListener('message', handler);
                resolve(event.data);
            }
        }

        window.addEventListener('message', handler);
        setTimeout(() => reject(new Error("Took too long (>5s)")), 5000);
    });
}

// sandbox -> offscreen
function respondToB2WMessage(payload: B2WResponseMessage["payload"], event: MessageEvent<B2WRequestMessage>) {
    event.source!.postMessage({
        message: B2W_RESPONSE_MESSAGE_NAME,
        uuid: event.data.uuid,
        payload,
    } satisfies B2WResponseMessage, { targetOrigin: event.origin })
}

let REGISTERED_CUSTOM_STATS_BY_NAME: Map<string, JSCustomStatInternal<any, any>> = new Map();
let REGISTERED_CUSTOM_STATS_BY_FILENAME: Map<string, JSCustomStatInternal<any, any>[]> = new Map();

async function registerCustomStatFromSrc(src: string, filename: string, event: MessageEvent<any>) {
    const objectURL = URL.createObjectURL(new Blob([src], { type: 'text/javascript' }));
    const moduleNamespace = await import(/* @vite-ignore */ objectURL);
    const stats = Object.values(moduleNamespace).filter(isJSCustomStatInternal);
    URL.revokeObjectURL(objectURL);
    respondToB2WMessage({ registerCustomStatFromSrcPercentileProperties: stats.map(stat => stat.property) }, event);
    REGISTERED_CUSTOM_STATS_BY_FILENAME.set(filename, stats);
    for (const stat of stats) {
        REGISTERED_CUSTOM_STATS_BY_NAME.set(stat.property.value, stat);
        console.log(stat.property.value, stat);
    }
}

window.addEventListener('message', async event => {
    if (!isB2WRequestMessage(event.data)) {
        return;
    }

    const payload = event.data.payload;

    if ('registerCustomStatFromSrc' in payload) {
        registerCustomStatFromSrc(payload.registerCustomStatFromSrc, payload.filename, event).then(_ => {
            respondToB2WMessage({}, event);
        });
        return true;
    }

    if ('removeCustomStatByFilename' in payload) {
        for (const stat of REGISTERED_CUSTOM_STATS_BY_FILENAME.get(payload.removeCustomStatByFilename) ?? []) {
            REGISTERED_CUSTOM_STATS_BY_NAME.delete(stat.property.value);
        }

        REGISTERED_CUSTOM_STATS_BY_FILENAME.delete(payload.removeCustomStatByFilename);
        respondToB2WMessage({}, event);
    }

    if ('createCacheFor' in payload) {
        const stat = REGISTERED_CUSTOM_STATS_BY_NAME.get(payload.createCacheFor);
        if (stat === undefined) {
            respondToB2WMessage({ error: `stat ${payload.createCacheFor} does not exist.` }, event);
            return true;
        }
        respondToB2WMessage({
            createCacheFor: stat.create_cache()
        }, event);
        return true;
    }

    if ('onIncremental' in payload) {
        const stat = REGISTERED_CUSTOM_STATS_BY_NAME.get(payload.onIncremental);
        if (stat === undefined) {
            respondToB2WMessage({ error: `stat ${payload.onIncremental} does not exist.` }, event);
            return true;
        }
        stat.on_incremental(payload.cache);
        respondToB2WMessage({ cacheUpdate: payload.cache }, event);
        return true;
    }

    if ('apply' in payload) {
        const stat = REGISTERED_CUSTOM_STATS_BY_NAME.get(payload.apply);
        if (stat === undefined) {
            respondToB2WMessage({ error: `stat ${payload.apply} does not exist.` }, event);
            return true;
        }

        const rows = Papa.parse<StatcastRow>(payload.rows, { header: true, dynamicTyping: true });
        const subsidiaryRows = payload.subsidiaryRows == null ? null : Papa.parse<SubsidiaryRow>(payload.subsidiaryRows, { header: true, dynamicTyping: true });
        stat.apply(payload.cache, rows.data, subsidiaryRows?.data);
        respondToB2WMessage({ cacheUpdate: payload.cache }, event);
        return true;
    }

    if ('onFinishApply' in payload) {
        const stat = REGISTERED_CUSTOM_STATS_BY_NAME.get(payload.onFinishApply);
        if (stat === undefined) {
            respondToB2WMessage({ error: `stat ${payload.onFinishApply} does not exist.` }, event);
            return true;
        }

        respondToB2WMessage({
            onFinishApply: stat.on_finish_apply(payload.cache),
            cacheUpdate: payload.cache,
        }, event);
        return true;
    }

    if ('valueFor' in payload) {
        const stat = REGISTERED_CUSTOM_STATS_BY_NAME.get(payload.valueFor);
        if (stat === undefined) {
            respondToB2WMessage({ error: `stat ${payload.valueFor} does not exist.` }, event);
            return true;
        }
        respondToB2WMessage({
            valueFor: stat.value(payload.value)
        }, event);
        return true;
    }

    if ('samplesFor' in payload) {
        const stat = REGISTERED_CUSTOM_STATS_BY_NAME.get(payload.samplesFor);
        if (stat === undefined) {
            respondToB2WMessage({ error: `stat ${payload.samplesFor} does not exist.` }, event);
            return true;
        }
        respondToB2WMessage({
            samplesFor: stat.samples(payload.value)
        }, event);
        return true;
    }
});
