import type {StatcastRow} from "@/utils/shared/data_types/autogenerated-statcast-row.ts";

export interface CustomStat<Self> {
    /** `snake_case` */
    name: string;

    apply(rows: StatcastRow[], map: Record<string, Self>): void;

    value(self: Self): number;

    value_pretty(self: Self): number;
}

export function distributionData<T extends CustomStat<T>>(stat: T, by_player: Record<string, T>, qualifiedPitchers: Set<number>): [number, number] {
    const values = Object.entries(by_player).filter(([key, _]) => qualifiedPitchers.has(Number(key))).map(([_, instance]) => stat.value(instance));

    const mean = values.reduce((a, b) => a + b, 0) / values.length;
    const variance = values.reduce((acc, value) => acc + Math.pow(value - mean, 2), 0) / values.length;

    return [mean, Math.sqrt(variance)];
}
