import {type CustomStat} from "@/utils/stats/custom_stats";
import type {StatcastRow} from "@/utils/data_types/autogenerated-statcast-row.ts";
import Papa from "papaparse";
import Comlink from "comlink";

export let REGISTERED_CUSTOM_STATS: CustomStat<any>[] = [];

function getCustomStatForName(name: string): CustomStat<any> | undefined {
    return REGISTERED_CUSTOM_STATS.find(stat => stat.property.value === name);
}

function onCustomStatParse(stats: CustomStat<any>[]) {
    REGISTERED_CUSTOM_STATS = stats;
    const properties = stats.map(stat => stat.property);

}

export const WORKER_API = {
    applyRowsForDate(data_string: string, cache: Record<string, object>, stat_name: string): Record<string, object> {
        const stat: CustomStat<any> = getCustomStatForName(stat_name)!;

        const data: Papa.ParseResult<StatcastRow> = Papa.parse(data_string, {
            header: true,
            dynamicTyping: true,
        });

        stat.apply(data.data, cache);

        return cache;
    },

    getDistributionData(stat_name: string, cache: Record<string, object>): [number, number] {
        const stat: CustomStat<any> = getCustomStatForName(stat_name)!;
        const values = Object.values(cache).filter(instance => stat.is_qualified(instance, stat.property.qualification_threshold)).map(instance => stat.value(instance));

        const mean = values.reduce((a, b) => a + b, 0) / values.length;
        const variance = values.reduce((acc, value) => acc + Math.pow(value - mean, 2), 0) / values.length;

        return [mean, Math.sqrt(variance)];
    },

    getValueData(stat_name: string, cache: Record<string, object>): Map<object, number> {
        const stat: CustomStat<any> = getCustomStatForName(stat_name)!;
        const map = new Map<object, number>();
        for (const obj of Object.values(cache)) {
            map.set(obj, stat.value(obj));
        }
        return map;
    },


};

window.addEventListener('message', e => {
    Comlink.expose(WORKER_API, e.ports[0]);
}, { once: true });
