import type {StatcastRow} from "@/utils/data_types/autogenerated-statcast-row";
import type {ExtendedPercentileProperty} from "@/utils/stats";

export interface CustomStat<Self> {
    property: ExtendedPercentileProperty;

    apply(rows: StatcastRow[], map: Record<string, Self>): void;

    value(self: Self): number;

    is_qualified(self: Self, threshold: number): boolean;
}
