import type {StatcastRow} from "@/utils/data_types/autogenerated-statcast-row";
import {type ExtendedPercentileProperty, isExtendedPercentileProperty} from "@/utils/stats";
import type {SubsidiaryRow} from "@/utils/data_types/subsidiary-row.ts";

export type BaseCache<T extends object | string> = {
    by_player: Record<string, T>,
    cached_dates: string[],
    qualification_threshold?: number,
};

export type CustomStat<T extends object | string, Cache extends BaseCache<T> = BaseCache<T>> = JSCustomStat<T, Cache> | WASMCustomStat<T, Cache>;

export interface WASMCustomStat<T extends object | string, Cache extends BaseCache<T> = BaseCache<T>> {
    property: ExtendedPercentileProperty;

    deserialize_cache(cache?: Cache): boolean;

    serialize_cache(): Cache;

    on_incremental(): void;

    apply(unparsed_csv_data: Uint8Array<ArrayBuffer>, unparsed_subsidiary_csv_data: Uint8Array<ArrayBuffer> | null): void;

    on_finish_apply(): 'rerun' | false;

    value(value: T): number;

    samples(value: T): number;
}

export interface JSCustomStat<T extends object | string, Cache extends BaseCache<T> = BaseCache<T>> {
    property: ExtendedPercentileProperty;

    create_cache(): Cache;

    on_incremental(cache: Cache): void;

    apply(cache: Cache, rows: StatcastRow[], subsidiary_rows: SubsidiaryRow[] | undefined | null): void;

    on_finish_apply(cache: Cache): 'rerun' | false;

    value(value: T): number;

    samples(value: T): number;
}

export function isWASMCustomStat(value: any): value is WASMCustomStat<any> {
    return typeof value === "object"
        && isExtendedPercentileProperty(value.property)
        && typeof value.deserialize_cache === "function"
        && typeof value.serialize_cache === "function"
        && typeof value.on_incremental === "function"
        && typeof value.apply === "function"
        && typeof value.on_finish_apply === "function"
        && typeof value.value === "function"
        && typeof value.samples === "function";
}

export function isJSCustomStat(value: any): value is JSCustomStat<any, any> {
    return typeof value === "object"
        && isExtendedPercentileProperty(value.property)
        && typeof value.create_cache === "function"
        && typeof value.on_incremental === "function"
        && typeof value.apply === "function"
        && typeof value.on_finish_apply === "function"
        && typeof value.value === "function"
        && typeof value.samples === "function"
}
