import type {StatcastRow} from "@/utils/data_types/autogenerated-statcast-row";
import {type ExtendedPercentileProperty, isExtendedPercentileProperty} from "@/utils/stats";

export type BaseCache<T extends object> = {
    by_player: Record<string, T>,
    cached_dates: string[],
    qualification_threshold?: number,
};

export interface CustomStat<T extends object, Cache extends BaseCache<T> = BaseCache<T>> {
    property: ExtendedPercentileProperty;

    create_cache(): Cache;

    on_incremental(cache: Cache): void;

    apply(rows: StatcastRow[], cache: Cache): void;

    on_finish_apply(cache: Cache): 'rerun' | false;

    value(value: T): number;

    samples(value: T): number;
}

export function isCustomStat(value: any): value is CustomStat<any, any> {
    return typeof value === "object"
        && isExtendedPercentileProperty(value.property)
        && typeof value.create_cache === "function"
        && typeof value.on_incremental === "function"
        && typeof value.apply === "function"
        && typeof value.on_finish_apply === "function"
        && typeof value.value === "function"
        && typeof value.samples === "function";
}
