import Papa from 'papaparse';

import {type DBSchema, type IDBPDatabase, openDB} from 'idb';
import type {StatcastRow} from "@/utils/shared/data_types/autogenerated-statcast-row";
import {type CustomStat, distributionData} from "@/utils/shared/stats/custom_stats";
import {qualifiedPitchers} from "@/utils/extension/statsapi";
import {ENABLED_SEASONS, CALCULATED_STATS} from "@/utils/shared/statcast";

export async function getStatcastData() {
    const db = await createDB();

    await cacheQualifiedPitchersBySeason();

    await cacheStatcastData(db);

    await calculateStats(db);
}

export interface StatcastDB extends DBSchema {
    date: {
        key: string;
        value: string;
    };
    stats: {
        key: [number, string];
        value: StatCache<any>;
    };
}

type StatCache<T> = {
    cachedDates: string[],
    byPlayer: Record<string, T>,
}

const DISTRIBUTION_METRICS: Record<string, [number, number]> = {};

const QUALIFIED_PITCHERS_BY_SEASON: Record<number, Set<number>> = {};

async function createDB(): Promise<IDBPDatabase<StatcastDB>> {
    return openDB<StatcastDB>('statcast-data', 1, {
        upgrade(db) {
            db.createObjectStore('date');
            db.createObjectStore('stats');
        }
    });
}

async function cacheQualifiedPitchersBySeason() {
    console.log('Getting qualified pitchers per season...');
    for (const season of ENABLED_SEASONS) {
        QUALIFIED_PITCHERS_BY_SEASON[season] = new Set(await qualifiedPitchers(season));
    }
    console.debug(QUALIFIED_PITCHERS_BY_SEASON);
}

async function cacheStatcastData(db: IDBPDatabase<StatcastDB>) {
    console.log('Parsing statcast data...');
    for (const season of ENABLED_SEASONS) {
        await recacheAllPlays(season, db);
    }
}

async function calculateStats(db: IDBPDatabase<StatcastDB>) {
    console.log('Calculating stats...');
    for (const stat of CALCULATED_STATS) {
        for (const season of ENABLED_SEASONS) {
            console.log('Calculating ' + stat.name + '...');

            const cache: StatCache<any> | undefined = (await db.get('stats', [season, stat.name])) ?? { cachedDates: [], byPlayer: {} };

            const newDates = seasonDates(season).filter(date => !cache.cachedDates.includes(date)).toArray();

            for (const date of newDates) {
                const data = await getDayFromDB(date, db);
                stat.apply(data.data.filter(r => r.game_type === 'R'), cache.byPlayer);
            }
            cache.cachedDates.push(...newDates);

            DISTRIBUTION_METRICS[`${season}:${stat.name}`] = distributionData(stat, cache.byPlayer, QUALIFIED_PITCHERS_BY_SEASON[season] ?? new Set());

            await db.put('stats', cache, [season, stat.name]);
        }
    }
}

function* seasonDates(season: number): Generator<string> {
    const toIsoDate: (date: Date) => string = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;

    const today = new Date().setHours(0, 0, 0, 0);

    const start = new Date(season, 3 - 1, 15);
    const end = new Date(season, 11 - 1, 15);

    for (let date = new Date(start); date <= end && Number(date) < today; date.setDate(date.getDate() + 1)) {
        yield toIsoDate(date);
    }
}

export async function getStatFromDB<T extends object>(stat: CustomStat<T>, season: number, player: number, db: IDBPDatabase<StatcastDB>): Promise<T | undefined> {
    const cache: StatCache<T> | undefined = await db.get('stats', [season, stat.name]);

    if (cache === undefined) {
        return undefined;
    }

    return cache.byPlayer[String(player)];
}

export function getDistributionData<T>(stat: CustomStat<T>, season: number): { mean: number, stdev: number } {
    const [mean, stdev] = DISTRIBUTION_METRICS[`${season}:${stat.name}`] ?? [0, 1];
    return { mean, stdev };
}

export async function getSampleNumberFromDB<T extends object>(stat: CustomStat<T>, season: number, db: IDBPDatabase<StatcastDB>): Promise<number> {
    const cache: StatCache<T> | undefined = await db.get('stats', [season, stat.name]);

    if (cache === undefined) {
        return 0;
    }

    return Object.keys(cache.byPlayer).length;
}

async function recacheAllPlays(season: number, db: IDBPDatabase<StatcastDB>) {
    const allDates = await db.getAllKeys('date');

    for (const date of seasonDates(season)) {
        if (!allDates.includes(date)) {
            const result = await getDayFromURL(date);
            if (result !== null) {
                await db.put('date', result, date);
            }
        }
    }
}

async function getDayFromURL(date: string): Promise<string | null> {
    const URL: (start_dt: string, end_dt: string) => string = (start_dt, end_dt) => `https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7CPO%7CS%7C=&hfSea=&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=${start_dt}&game_date_lt=${end_dt}&team=&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0&type=details&`;

    const result = await fetch(URL(date, date));
    if (!result.ok) {
        return null;
    }

    return result.text();
}

async function getDayFromDB(date: string, db: IDBPDatabase<StatcastDB>): Promise<Papa.ParseResult<StatcastRow>> {
    return Papa.parse(await db.get('date', date) ?? '', {
        header: true,
        dynamicTyping: true,
    });
}
