import type { IDBPDatabase } from "idb";
import {DISTRIBUTION_METRICS, type StatCache, type StatcastDB} from "./statcast";
import Papa from "papaparse";
import type {PercentileProperty} from "@/utils/shared/stats";
import type {CustomStat} from "@/utils/shared/stats/custom_stats";
import type {StatcastRow} from "@/utils/shared/data_types/autogenerated-statcast-row.ts";

export function* seasonDates(season: number): Generator<string> {
    const toIsoDate: (date: Date) => string = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;

    const today = new Date().setHours(0, 0, 0, 0);

    const start = new Date(season, 3 - 1, 15);
    const end = new Date(season, 11 - 1, 15);

    for (let date = new Date(start); date <= end && Number(date) < today; date.setDate(date.getDate() + 1)) {
        yield toIsoDate(date);
    }
}

export function getDistributionData(stat: PercentileProperty, season: number): { mean: number, stdev: number } | undefined {
    const result = DISTRIBUTION_METRICS[`${season}:${stat.value}`];
    if (result === undefined) {
        return undefined;
    } else {
        const [mean, stdev] = result;
        return { mean, stdev };
    }
}

export async function getStatFromDB<T extends object>(stat: CustomStat<T>, season: number, player: number, db: IDBPDatabase<StatcastDB>): Promise<T | undefined> {
    const cache: StatCache<T> | undefined = await db.get('stats', [season, stat.property.value]);

    if (cache === undefined) {
        return undefined;
    }

    return cache.byPlayer[String(player)];
}

export async function getDayFromURL(date: string): Promise<string | null> {
    const URL: string = `https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7CPO%7CS%7C=&hfSea=&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=${date}&game_date_lt=${date}&team=&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0&type=details&`;

    const result = await fetch(URL);
    if (!result.ok) {
        return null;
    }

    return result.text();
}

export async function getDayFromDB(date: string, db: IDBPDatabase<StatcastDB>): Promise<Papa.ParseResult<StatcastRow>> {
    return Papa.parse(await db.get('date', date) ?? '', {
        header: true,
        dynamicTyping: true,
    });
}