import type {StatcastRow} from "@/utils/data_types/autogenerated-statcast-row";
import {type ExtendedPercentileProperty, isExtendedPercentileProperty} from "@/utils/stats";
import type {SubsidiaryRow} from "@/utils/data_types/subsidiary-row.ts";

export interface StatCache<T extends object | string> {
    /** The actual cache of entry by MLB player id. */
    by_player: Record<string, T>,
    /** List of already calculated dates. */
    cached_dates: string[],
    /** If left unsupplied, calculated as 25% of the max samples (by player) */
    qualification_threshold?: number,
    /** If true, will supply rttv.ca subsidiary CSV data */
    uses_subsidiary_csv?: boolean,

    [key: string]: unknown,
};

export interface WASMCustomStat<T extends object | string> {
    property: ExtendedPercentileProperty;

    deserialize_cache(cache?: StatCache<T>): boolean;

    serialize_cache(): StatCache<T>;

    on_incremental(): void;

    apply(unparsed_csv_data: Uint8Array<ArrayBuffer>, unparsed_subsidiary_csv_data: Uint8Array<ArrayBuffer> | null): void;

    on_finish_apply(): 'rerun' | false;

    value(value: T): number;

    samples(value: T): number;
}

export interface JSCustomStat<T extends object | string> {
    property: ExtendedPercentileProperty;

    create_cache(): Promise<StatCache<T>>;

    on_incremental(cache: StatCache<T>): Promise<void>;

    apply(cache: StatCache<T>, rows: Uint8Array<ArrayBuffer>, subsidiary_rows: Uint8Array<ArrayBuffer> | undefined | null): Promise<void>;

    on_finish_apply(cache: StatCache<T>): Promise<'rerun' | false>;

    value(value: T): Promise<number>;

    samples(value: T): Promise<number>;
}

export interface JSCustomStatInternal<T extends object | string> {
    property: ExtendedPercentileProperty;

    create_cache(): StatCache<T>;

    on_incremental(cache: StatCache<T>): void;

    apply(cache: StatCache<T>, rows: StatcastRow[], subsidiary_rows: SubsidiaryRow[] | undefined | null): void;

    on_finish_apply(cache: StatCache<T>): 'rerun' | false;

    value(value: T): number;

    samples(value: T): number;
}

export function isWASMCustomStat(value: any): value is WASMCustomStat<any> {
    return typeof value === "object"
        && isExtendedPercentileProperty(value.property)
        && typeof value.deserialize_cache === "function"
        && typeof value.serialize_cache === "function"
        && typeof value.on_incremental === "function"
        && typeof value.apply === "function"
        && typeof value.on_finish_apply === "function"
        && typeof value.value === "function"
        && typeof value.samples === "function";
}

export function isJSCustomStat(value: any): value is JSCustomStat<any> {
    return typeof value === "object"
        && isExtendedPercentileProperty(value.property)
        && typeof value.create_cache === "function"
        && typeof value.on_incremental === "function"
        && typeof value.apply === "function"
        && typeof value.on_finish_apply === "function"
        && typeof value.value === "function"
        && typeof value.samples === "function"
}

export function isJSCustomStatInternal(value: any): value is JSCustomStatInternal<any> {
    // identical-looking as of rn without getting the parameter types, which isn't available at runtime in js.
    return isJSCustomStat(value);
}
