import type {ServerVals} from "@/utils/shared/data_types/autogenerated-server-vals.ts";
import {ENABLED_SEASONS, type MessageResponse, STATS} from "@/utils/shared/statcast.ts";
import {type CustomStat} from "@/utils/shared/custom_stats";
import {sendMessage} from "@/utils/main/send-message.ts";
import {zScoreToPercentile} from "@/utils/shared/math.ts";

async function getStatFromDB(stat: CustomStat<any>, season: number, player: number): Promise<object | undefined> {
    const response: MessageResponse<object> = (await sendMessage({ type: 'getStatFromDB', stat: stat.name, season, player }))!;
    if (response.error !== undefined) {
        console.error(response.error);
        return undefined;
    }

    return response.result!;
}

async function getDistributionData(stat: CustomStat<any>, season: number): Promise<{ mean: number, stdev: number } | undefined> {
    const response: MessageResponse<{ mean: number, stdev: number }> = await sendMessage({ type: 'getDistributionData', stat: stat.name, season });
    if (response.error !== undefined) {
        console.error(response.error);
        return undefined;
    }

    return response.result!;
}

export async function modifyServerVals(serverVals: ServerVals) {
    for (const stat of STATS) {
        for (const season of ENABLED_SEASONS) {
            const statcastSeason = serverVals.statcast.find(szn => szn.year === season);

            if (statcastSeason === undefined) {
                continue;
            }

            const request = getStatFromDB(stat, season, Number(serverVals.playerId));
            const request2 = getDistributionData(stat, season);

            const value = await request;
            if (value === undefined) {
                continue;
            }

            const value_pretty: string = stat.value_pretty(value);
            const { mean, stdev } = await request2 ?? { mean: 0, stdev: 1 };
            const percentile: number = zScoreToPercentile((stat.value(value) - mean) / stdev);
            (statcastSeason as any)[`${stat.name}`] = value_pretty;
            (statcastSeason as any)[`percent_rank_${stat.name}`] = Math.round(percentile);
            (statcastSeason as any)[`percent_rank_${stat.name}_unrounded`] = percentile;
        }

        serverVals.statcast.forEach(szn => {
            (szn as any)[`${stat.name}`] ??= null;
            (szn as any)[`percent_rank_${stat.name}`] ??= null;
            (szn as any)[`percent_rank_${stat.name}_unrounded`] ??= null;
        })
    }
}