import type {ServerVals} from "@/utils/shared/data_types/autogenerated-server-vals";
import type {ServerValsPatch} from "@/utils/shared/server-vals-patch";

export function applyServerValsPatch(serverVals: ServerVals, patches: ServerValsPatch) {
    if (serverVals.playerId !== String(patches.playerId)) {
        console.warn(`Incorrect player id for patch, expected ${patches.playerId} but found ${serverVals.playerId}`);
        return;
    }

    const keys = new Set(patches.patches.map(x => x.key));

    for (const patch of patches.patches) {
        const statcastSeason = serverVals.statcast.find(szn => szn.year === patch.season);

        if (statcastSeason === undefined) {
            continue;
        }

        (statcastSeason as any)[`${patch.key}`] = patch.value;
        (statcastSeason as any)[`percent_rank_${patch.key}`] = Math.round(patch.percentile ?? 0);
        (statcastSeason as any)[`percent_rank_${patch.key}_unrounded`] = patch.percentile;
    }

    for (const key of keys) {
        for (const statcastSeason of serverVals.statcast) {
            (statcastSeason as any)[`${key}`] ??= null;
            (statcastSeason as any)[`percent_rank_${key}`] ??= null;
            (statcastSeason as any)[`percent_rank_${key}_unrounded`] ??= null;
        }
    }

    for (const summary of patches.summaryPatches) {
        const year = serverVals.metricSummaryStats[String(summary.season)];

        if (year === undefined) {
            continue;
        }

        year[summary.metric] = {
            metric: summary.metric,
            avg_metric: summary.avg_metric,
            stddev_metric: summary.stddev_metric,
            n: String(summary.n),
        };
    }

    const forceDisplayYear = serverVals.statcast.at(-1);
    for (const patch of patches.forceDisplayPatches) {
        (forceDisplayYear! as any)[patch.metric] = 0;
    }
}
