export interface ServerVals {
    playerId:                   string;
    batSide:                    string;
    queryStrings:               QueryStrings;
    slug:                       string;
    playerName:                 string;
    playerType:                 string;
    playerTeam:                 string;
    playerCurrentTeam:          string;
    playerPosition:             string;
    playerIsActive:             string;
    mostRecentSeason:           string;
    currentSeason:              number;
    activeSeason:               string;
    rosterSearchSeason:         string;
    seasonState:                string;
    venueId:                    string;
    locale:                     string;
    stats:                      CareerStats;
    awards:                     Array<Award[]>;
    careerStats:                CareerStats;
    ytyStatRankings:            CareerStats;
    ytyMiLBStats:               CareerStats;
    hasStatcast:                string;
    hasBatterBatTracking:       boolean;
    hasFraming:                 string;
    hasOneKnee:                 string;
    hasCatcherFieldingRunValue: string;
    hasStatcastCatching:        string;
    hasOneKneeData:             string;
    hasPitchHandedBreakdown:    string;
    pitchHandedBreakdown:       PitchHandedBreakdownElement[] | CareerStats;
    isPitcher:                  boolean;
    awardBadges:                unknown[];
    rankings:                   CareerStats;
    statcast:                   Statcast[];
    metricSummaryStats:         { [key: string]: { [key: string]: MetricSummaryStat } };
    ytyFieldingStats:           CareerStats;
    statcastPitches:            StatcastPitches;
    pitchBreakdown:             PitchBreakdownElement[] | CareerStats;
    spinAxis:                   SpinAxi[] | CareerStats;
    spinAxisPitcher:            SpinAxisPitcherElement[] | CareerStats;
    rangeLine:                  RangeLine[];
    fielderPositioning:         FielderPositioningElement[] | CareerStats;
    zones:                      Zone[];
    zonesCompare:               null;
    zonesDiff:                  null;
    sprayData:                  null;
    sliceData:                  null;
    pitcherArsenal:             CareerStats;
    movement:                   MovementElement[] | CareerStats;
    pitchDistribution:          PitchDistributionElement[] | CareerStats;
    pitchTypeSamples:           PitchTypeSample[] | CareerStats;
    leaguePitchMovement:        LeaguePitchMovementElement[] | CareerStats;
    pitcherArmAngles:           PitcherArmAngle[] | CareerStats;
    pitchTypes:                 PitchType[];
    sprayChart:                 HasStatcastSprayChartElement[] | CareerStats;
    hasStatcastSprayChart:      HasStatcastSprayChartElement[] | CareerStats;
    statcastGameLogs:           StatcastGameLog[];
    statcastGameLogsFielding:   CareerStats;
    infieldDefense:             InfieldDefenseElement[] | CareerStats;
    statcastLeader:             StatcastLeader[];
    statcastHistogram:          StatcastHistogram[];
    pitchDetails:               PitchDetail[];
}

export interface Award {
    id:     string;
    name:   string;
    date:   Date;
    season: string;
    team:   Team;
    player: Player;
}

export interface Player {
    id:              number;
    link:            string;
    primaryPosition: PrimaryPosition;
}

export interface PrimaryPosition {
    code:         string;
    name:         string;
    type:         string;
    abbreviation: string;
}

export interface Team {
    id:       number;
    link:     string;
    teamName: string;
}

export interface CareerStats {
}

export interface FielderPositioningElement {
    year:                      string;
    is_sport_mlb:              number;
    is_sport_minors:           number;
    sport_id:                  number;
    fielder_id:                string;
    name_fielder:              string;
    fld_team_id:               string;
    fld_name_display_club:     string;
    fld_name_abbrev:           string;
    pos_id:                    string;
    n:                         string;
    avg_norm_start_pos_x:      number;
    avg_norm_start_pos_y:      number;
    avg_diff_from_league:      number;
    avg_diff_from_midpoint:    number;
    median_diff_from_midpoint: number;
    freq_close_to_midpoint:    number;
    freq_medium_from_midpoint: number;
    freq_far_from_midpoint:    number;
    avg_norm_start_distance:   number;
    avg_norm_start_angle:      number;
    season:                    number;
    start_distance:            number;
    start_angle:               number;
}

export interface HasStatcastSprayChartElement {
    x:         number;
    y:         number;
    events:    string;
    game_year: string;
    play_id:   string;
}

export interface InfieldDefenseElement {
    sort_order:                                        string;
    is_rollup_player:                                  string;
    is_rollup_team:                                    string;
    is_rollup_pos:                                     string;
    is_rollup_all:                                     string;
    name_display_first_last:                           string;
    name_display_last_first:                           string;
    fld_name_display_club:                             string;
    fld_abbreviation:                                  string;
    pos_name:                                          string;
    pos_name_short:                                    string;
    year:                                              string;
    player_id:                                         string;
    fld_team_id_display:                               string;
    primary_pos:                                       string;
    group_category:                                    string;
    actual_success_rate:                               number;
    adj_estimated_success_rate:                        number;
    diff_success_rate:                                 number;
    n:                                                 string;
    n_rhh:                                             string;
    n_lhh:                                             string;
    n_infront:                                         string;
    n_behind:                                          string;
    n_lateral_toward3bline:                            string;
    n_lateral_toward1bline:                            string;
    outs_above_average_rhh:                            number;
    outs_above_average_lhh:                            number;
    outs_above_average_infront:                        number;
    outs_above_average_behind:                         number;
    outs_above_average_lateral_toward3bline:           number;
    outs_above_average_lateral_toward1bline:           number;
    outs_above_average:                                number;
    actual_success_rate_formatted:                     number;
    adj_estimated_success_rate_formatted:              number;
    diff_success_rate_formatted:                       number;
    outs_above_average_formatted:                      number;
    outs_above_average_infront_formatted:              number;
    outs_above_average_behind_formatted:               number;
    outs_above_average_lateral_toward3bline_formatted: number;
    outs_above_average_lateral_toward1bline_formatted: number;
    outs_above_average_rhh_formatted:                  number;
    outs_above_average_lhh_formatted:                  number;
    full_year:                                         boolean;
}

export interface LeaguePitchMovementElement {
    year:                     string;
    pitch_hand:               string;
    num_pitchers:             string;
    n_ff:                     number;
    ff_avg_speed:             string;
    ff_avg_spin:              number | null;
    ff_avg_break_x:           string;
    ff_range_break_x:         string;
    ff_avg_break_z_induced:   string;
    ff_range_break_z_induced: string;
    n_ch:                     number;
    ch_avg_speed:             string;
    ch_avg_spin:              number | null;
    ch_avg_break_x:           string;
    ch_range_break_x:         string;
    ch_avg_break_z_induced:   string;
    ch_range_break_z_induced: string;
    n_cu:                     number;
    cu_avg_speed:             string;
    cu_avg_spin:              number | null;
    cu_avg_break_x:           string;
    cu_range_break_x:         string;
    cu_avg_break_z_induced:   string;
    cu_range_break_z_induced: string;
    n_fc:                     number;
    fc_avg_speed:             string;
    fc_avg_spin:              number | null;
    fc_avg_break_x:           string;
    fc_range_break_x:         string;
    fc_avg_break_z_induced:   string;
    fc_range_break_z_induced: string;
    n_fo:                     number | null;
    fo_avg_speed:             null | string;
    fo_avg_spin:              number | null;
    fo_avg_break_x:           null | string;
    fo_range_break_x:         null | string;
    fo_avg_break_z_induced:   null | string;
    fo_range_break_z_induced: null | string;
    n_kn:                     number | null;
    kn_avg_speed:             null | string;
    kn_avg_spin:              number | null;
    kn_avg_break_x:           null | string;
    kn_range_break_x:         null | string;
    kn_avg_break_z_induced:   null | string;
    kn_range_break_z_induced: null | string;
    n_sc:                     number | null;
    sc_avg_speed:             null | string;
    sc_avg_spin:              number | null;
    sc_avg_break_x:           null | string;
    sc_range_break_x:         null | string;
    sc_avg_break_z_induced:   null | string;
    sc_range_break_z_induced: null | string;
    n_si:                     number;
    si_avg_speed:             string;
    si_avg_spin:              number | null;
    si_avg_break_x:           string;
    si_range_break_x:         string;
    si_avg_break_z_induced:   string;
    si_range_break_z_induced: string;
    n_sl:                     number;
    sl_avg_speed:             string;
    sl_avg_spin:              number | null;
    sl_avg_break_x:           string;
    sl_range_break_x:         string;
    sl_avg_break_z_induced:   string;
    sl_range_break_z_induced: string;
    n_sv:                     number | null;
    sv_avg_speed:             null | string;
    sv_avg_spin:              number | null;
    sv_avg_break_x:           null | string;
    sv_range_break_x:         null | string;
    sv_avg_break_z_induced:   null | string;
    sv_range_break_z_induced: null | string;
    n_fs:                     number;
    fs_avg_speed:             string;
    fs_avg_spin:              number | null;
    fs_avg_break_x:           string;
    fs_range_break_x:         string;
    fs_avg_break_z_induced:   string;
    fs_range_break_z_induced: string;
    n_st:                     number | null;
    st_avg_speed:             null | string;
    st_avg_spin:              number | null;
    st_avg_break_x:           null | string;
    st_range_break_x:         null | string;
    st_avg_break_z_induced:   null | string;
    st_range_break_z_induced: null | string;
}

export interface MetricSummaryStat {
    metric:        string;
    avg_metric:    number;
    stddev_metric: number;
    n:             string;
}

export interface MovementElement {
    year:                                    string;
    pitcher_name:                            string;
    pitcher_id:                              string;
    team_name:                               string;
    team_name_abbrev:                        string;
    team_id:                                 string;
    pitch_hand:                              string;
    avg_speed:                               string;
    pitches_thrown:                          string;
    total_pitches:                           string;
    pitches_per_game:                        number;
    pitch_per:                               number;
    pitch_type:                              string;
    pitch_type_name:                         string;
    pitcher_break_z:                         number;
    pitcher_break_z_hidden:                  number;
    league_break_z:                          number | null;
    pitcher_break_z_induced:                 number;
    pitcher_break_z_induced_hidden:          number;
    league_break_z_induced:                  number | null;
    league_break_z_hidden:                   number | null;
    diff_z:                                  number | null;
    diff_z_hidden:                           number | null;
    rise:                                    null | string;
    rise_hidden:                             number | null;
    pitcher_break_x:                         number;
    pitcher_break_x_hidden:                  number;
    league_break_x:                          number | null;
    league_break_x_hidden:                   number | null;
    diff_x:                                  number | null;
    diff_x_hidden:                           number | null;
    tail:                                    null | string;
    tail_hidden:                             null | string;
    is_qualified:                            string;
    percent_rank_diff_z:                     number | null;
    percent_rank_diff_x:                     number | null;
    league_avg_speed_standard:               string;
    pitcher_break_z_standard:                number;
    pitcher_break_z_hidden_standard:         number;
    league_break_z_standard:                 number;
    league_break_z_hidden_standard:          number;
    diff_z_standard:                         number;
    diff_z_hidden_standard:                  number;
    pitcher_break_z_induced_standard:        number;
    pitcher_break_z_induced_hidden_standard: number;
    league_break_z_induced_standard:         number;
    league_break_z_induced_hidden_standard:  number;
    diff_z_induced_standard:                 number;
    diff_z_induced_hidden_standard:          number;
    pitcher_break_x_standard:                number;
    pitcher_break_x_hidden_standard:         number;
    league_break_x_standard:                 number;
    league_break_x_hidden_standard:          number;
    diff_x_standard:                         number;
    diff_x_hidden_standard:                  number;
    num_teams:                               number;
    year_odd_even:                           number;
    customClass:                             string;
}

export interface PitchBreakdownElement {
    percent:   number;
    count:     number;
    pitchType: string;
    color:     string;
    name:      string;
    season:    string;
}

export interface PitchDetail {
    api_pitch_type:               string;
    year:                         number;
    pitches:                      string;
    year_count:                   string;
    in_zone:                      string;
    out_zone:                     string;
    edge:                         string;
    barrels:                      null | string;
    hardhit:                      string;
    hard_hit_percent:             null | string;
    brl_percent:                  null | string;
    in_zone_swing:                string;
    out_zone_swing:               string;
    in_zone_swing_miss:           string;
    out_zone_swing_miss:          string;
    two_strike_pitches:           string;
    total_pitches:                string;
    lhb:                          string;
    rhb:                          string;
    release_speed:                string;
    year_odd_even:                number;
    bbe:                          null | string;
    hr:                           null | string;
    hits:                         null | string;
    singles:                      null | string;
    doubles:                      null | string;
    triples:                      null | string;
    k:                            null | string;
    pa:                           null | string;
    ab:                           null | string;
    swings:                       string;
    misses:                       string;
    gb_percent:                   null | string;
    ld_percent:                   null | string;
    fb_percent:                   null | string;
    pu_percent:                   null | string;
    ba:                           null | string;
    xba:                          null | string;
    bacon:                        null | string;
    xbacon:                       null | string;
    babip:                        null | string;
    obp:                          null | string;
    slg:                          null | string;
    xobp:                         null | string;
    xslg:                         null | string;
    iso:                          null | string;
    xiso:                         null | string;
    woba:                         null | string;
    xwoba:                        null | string;
    wobacon:                      null | string;
    xwobacon:                     null | string;
    xbadiff:                      null | string;
    xslgdiff:                     null | string;
    wobadiff:                     null | string;
    bb_percent:                   null | string;
    k_percent:                    null | string;
    swing:                        string;
    whiff_percent:                null | string;
    avg_ev:                       null | string;
    avg_la:                       null | string;
    avg_spin:                     string;
    avg_break_x:                  string;
    avg_plate_z:                  string;
    avg_plate_x:                  string;
    avg_release_z:                string;
    avg_release_x:                string;
    avg_extension:                string;
    avg_break_z_without_gravity:  string;
    avg_break_z_with_gravity:     string;
    batted_ball_pull:             string;
    batted_ball_oppo:             string;
    batted_ball_straight:         string;
    arm_angle:                    null | string;
    bat_speed:                    null | string;
    swing_length:                 null | string;
    attack_angle:                 number | null;
    attack_direction_pullopp:     number | null;
    swing_path_tilt:              number | null;
    intercept_x:                  null | string;
    intercept_y:                  null | string;
    ideal_attack_angle_rate:      null | string;
    pitch_percent:                string;
    in_zone_percent:              string;
    out_zone_percent:             string;
    edge_percent:                 string;
    swing_percent:                string;
    barrel_per_pa_percent:        null | string;
    z_swing_percent:              null | string;
    oz_swing_percent:             string;
    z_swing_miss_percent:         null | string;
    oz_swing_miss_percent:        null | string;
    put_away_percent:             null | string;
    batted_ball_oppo_percent:     null | string;
    batted_ball_pull_percent:     null | string;
    batted_ball_straight_percent: null | string;
}

export interface PitchDistributionElement {
    name_display_last_first: string;
    name_display_first_last: string;
    year:                    string;
    player_id:               string;
    bin_speed:               string;
    n_pitches:               string;
    freq_all:                number;
    freq_ff:                 number;
    freq_ch:                 number;
    freq_cu:                 number;
    freq_fc:                 number;
    freq_fo:                 number;
    freq_kn:                 number;
    freq_sc:                 number;
    freq_si:                 number;
    freq_sl:                 number;
    freq_sv:                 number;
    freq_fs:                 number;
    freq_st:                 number;
    throws:                  string;
    pitch_hand:              string;
    freq_ff_lg:              string;
    freq_ch_lg:              string;
    freq_cu_lg:              string;
    freq_fc_lg:              string;
    freq_fo_lg:              null | string;
    freq_kn_lg:              string;
    freq_sc_lg:              null | string;
    freq_si_lg:              string;
    freq_sl_lg:              string;
    freq_sv_lg:              string;
    freq_fs_lg:              string;
    freq_st_lg:              string;
    freq_ff_player:          number;
    freq_ch_player:          null;
    freq_cu_player:          number | null;
    freq_fc_player:          number | null;
    freq_fo_player:          number | null;
    freq_kn_player:          null;
    freq_sc_player:          null;
    freq_si_player:          number | null;
    freq_sl_player:          number | null;
    freq_sv_player:          null;
    freq_fs_player:          number | null;
    freq_st_player:          number | null;
}

export interface PitchHandedBreakdownElement {
    year:      string;
    yearData:  YearDatum[];
    L_pitches: number;
    R_pitches: number;
}

export interface YearDatum {
    api_pitch_type_group03: string;
    R:                      number;
    L:                      number;
    R_percent:              number;
    L_percent:              number;
    total:                  number;
    all_percent:            number;
    pitch_name:             string;
    pitch_abbrev:           string;
    pitch_color:            string;
    pitch_outline_color:    string;
}

export interface PitchTypeSample {
    year:                       number;
    is_sport_mlb:               number;
    is_sport_minors:            number;
    sport_id:                   number;
    pitcher:                    number;
    pitch_hand:                 string;
    api_pitch_type:             string;
    game_pk:                    number;
    play_id:                    string;
    api_p_release_speed:        string;
    api_p_release_spin_rate:    number | null;
    api_break_x_inches:         number;
    api_break_z_induced_inches: number;
    total_break_inches:         number;
    diff_break_inches:          number;
    play_url:                   string;
}

export interface PitchType {
    pitch_type_group: string;
    pitch_name:       string;
}

export interface PitcherArmAngle {
    pitcher:            number;
    year:               number;
    pitch_hand:         string;
    ball_angle_rounded: number;
    n_pitches:          number;
    arm_angle?:         number;
}

export interface QueryStrings {
    stats?:      string;
    playerType?: string;
}

export interface RangeLine {
    player_id:                      number;
    play_id:                        string;
    name_display_first_last:        string;
    stars:                          number;
    distance:                       string;
    pos:                            number;
    opportunity_time:               string;
    out:                            number;
    wall:                           number;
    back:                           number;
    landing_pos_x_10:               number;
    landing_pos_y_10:               number;
    player_avg_norm_start_pos_x_10: number;
    player_avg_norm_start_pos_y_10: number;
    catch_rate:                     string;
}

export interface SpinAxi {
    player_name_last_first:          string;
    player_name_first_last:          string;
    team_id:                         number;
    team_name:                       string;
    file_code:                       string;
    team_name_abbrev:                string;
    season:                          number;
    is_sport_mlb:                    number;
    is_sport_minors:                 number;
    sport_id:                        number;
    player_id:                       number;
    pitch_hand:                      string;
    pov_code:                        string;
    api_pitch_type:                  string;
    api_pitch_name:                  string;
    n_pitches:                       number;
    release_speed:                   string;
    spin_rate:                       number;
    movement_inches:                 string;
    alan_active_spin_pct:            number;
    active_spin:                     number;
    image_spin_x:                    number;
    image_spin_y:                    number;
    image_spin_z:                    number;
    hawkeye_measured:                number;
    movement_inferred:               number;
    image_orientation_angle:         number;
    active_spin_formatted:           number;
    hawkeye_measured_clock_minutes:  number;
    movement_inferred_clock_minutes: number;
    diff_measured_inferred:          number;
    diff2:                           number;
    diff_measured_inferred_minutes:  number;
    hawkeye_measured_clock_hh:       number;
    hawkeye_measured_clock_mm:       number;
    movement_inferred_clock_hh:      number;
    movement_inferred_clock_mm:      number;
    diff_clock_hh:                   number;
    diff_clock_mm:                   number;
    hawkeye_measured_clock_label:    string;
    movement_inferred_clock_label:   string;
    diff_clock_label:                string;
    hidden_year:                     boolean;
    even_year:                       boolean;
}

export interface SpinAxisPitcherElement {
    player_name_last_first: string;
    player_name_first_last: string;
    season:                 number;
    player_id:              number;
    pitch_hand:             string;
    pov_code:               string;
    n_tot_pitches:          number;
    rn_clock:               number;
    meas_n_pitches:         number;
    meas_n_ff:              number;
    meas_n_si:              number;
    meas_n_fc:              number;
    meas_n_ch:              number;
    meas_n_fs:              number;
    meas_n_fo:              number;
    meas_n_sc:              number;
    meas_n_sl:              number;
    meas_n_st:              number;
    meas_n_sv:              number;
    meas_n_cu:              number;
    meas_n_cs:              number;
    meas_n_kc:              number;
    meas_n_kn:              number;
    meas_n_ep:              number;
    meas_n_fa:              number;
    meas_freq_ff:           number;
    meas_freq_si:           number;
    meas_freq_fc:           number;
    meas_freq_ch:           number;
    meas_freq_fs:           number;
    meas_freq_fo:           number;
    meas_freq_sc:           number;
    meas_freq_sl:           number;
    meas_freq_st:           number;
    meas_freq_sv:           number;
    meas_freq_cu:           number;
    meas_freq_cs:           number;
    meas_freq_kc:           number;
    meas_freq_kn:           number;
    meas_freq_ep:           number;
    meas_freq_fa:           number;
    infer_n_pitches:        number;
    infer_n_ff:             number;
    infer_n_si:             number;
    infer_n_fc:             number;
    infer_n_ch:             number;
    infer_n_fs:             number;
    infer_n_fo:             number;
    infer_n_sc:             number;
    infer_n_sl:             number;
    infer_n_st:             number;
    infer_n_sv:             number;
    infer_n_cu:             number;
    infer_n_cs:             number;
    infer_n_kc:             number;
    infer_n_kn:             number;
    infer_n_ep:             number;
    infer_n_fa:             number;
    infer_freq_ff:          number;
    infer_freq_si:          number;
    infer_freq_fc:          number;
    infer_freq_ch:          number;
    infer_freq_fs:          number;
    infer_freq_fo:          number;
    infer_freq_sc:          number;
    infer_freq_sl:          number;
    infer_freq_st:          number;
    infer_freq_sv:          number;
    infer_freq_cu:          number;
    infer_freq_cs:          number;
    infer_freq_kc:          number;
    infer_freq_kn:          number;
    infer_freq_ep:          number;
    infer_freq_fa:          number;
    rn_clock_sort:          number;
    x?:                     string;
    y?:                     number;
}

export interface Statcast {
    aggregate:                                       string;
    year:                                            number | null;
    yearhidden:                                      number;
    is_sport_mlb:                                    number;
    is_sport_milb:                                   number;
    sport_id:                                        number;
    player_id:                                       number;
    age:                                             number | null;
    bat_side:                                        string;
    pitch_hand:                                      string;
    month:                                           string;
    grouping_code:                                   string;
    grouping_cat:                                    string;
    pitch_count:                                     number;
    in_zone_percent:                                 number;
    out_zone_percent:                                number;
    edge_percent:                                    number;
    z_swing_percent:                                 number;
    oz_swing_percent:                                number;
    iz_contact_percent:                              number;
    oz_contact_percent:                              number;
    whiff_percent:                                   number;
    f_strike_percent:                                number;
    f_swing_percent:                                 number;
    swing_percent:                                   number;
    meatball_swing_percent:                          number;
    meatball_percent:                                number;
    z_swing_miss_percent:                            number;
    oz_swing_miss_percent:                           number;
    in_zone:                                         number;
    out_zone:                                        number;
    edge:                                            number;
    popups:                                          number;
    flyballs:                                        number;
    linedrives:                                      number;
    groundballs:                                     number;
    airballs:                                        number;
    popups_percent:                                  number;
    flyballs_percent:                                number;
    linedrives_percent:                              number;
    groundballs_percent:                             number;
    airballs_percent:                                number;
    pull_percent:                                    number;
    straightaway_percent:                            number;
    opposite_percent:                                number;
    pull_percent_airballs:                           number;
    straightaway_percent_airballs:                   number;
    opposite_percent_airballs:                       number;
    pull_percent_groundballs:                        number;
    straightaway_percent_groundballs:                number;
    opposite_percent_groundballs:                    number;
    pull_percent_popups:                             number;
    straightaway_percent_popups:                     number;
    opposite_percent_popups:                         number;
    pull_percent_flyballs:                           number;
    straightaway_percent_flyballs:                   number;
    opposite_percent_flyballs:                       number;
    pull_percent_linedrives:                         number;
    straightaway_percent_linedrives:                 number;
    opposite_percent_linedrives:                     number;
    poorlyweak_percent:                              number;
    poorlytopped_percent:                            number;
    poorlyunder_percent:                             number;
    flareburner_percent:                             number;
    solidcontact_percent:                            number;
    hr_flyballs_percent:                             number;
    in_zone_swing:                                   number;
    out_zone_swing:                                  number;
    in_zone_swing_miss:                              number;
    out_zone_swing_miss:                             number;
    pitch_count_fastball:                            number;
    pitch_count_offspeed:                            number;
    pitch_count_breaking:                            number;
    pa:                                              number;
    ab:                                              number;
    hit:                                             number;
    single:                                          number;
    double:                                          number;
    triple:                                          number;
    home_run:                                        number;
    walk:                                            number;
    strikeout:                                       number;
    hbp:                                             number;
    k_percent:                                       number;
    bb_percent:                                      number;
    sz_judge:                                        number;
    batted_ball:                                     number;
    barrel:                                          number;
    barrel_batted_rate:                              number;
    barrels_per_pa:                                  number;
    launch_angle_avg:                                string;
    exit_velocity_avg:                               string;
    exit_velocity_max:                               string;
    hard_hit_percent:                                number;
    sweet_spot_percent:                              number;
    ba:                                              string;
    xba:                                             string;
    bacon:                                           string;
    xbacon:                                          string;
    babip:                                           string;
    obp:                                             string;
    slg:                                             string;
    xobp:                                            string;
    xslg:                                            string;
    iso:                                             string;
    xiso:                                            string;
    woba:                                            string;
    xwoba:                                           string;
    wobacon:                                         string;
    xwobacon:                                        string;
    xbadiff:                                         string;
    xslgdiff:                                        string;
    wobadiff:                                        string;
    player_type:                                     string;
    era:                                             number | null;
    xera:                                            number | null;
    avg_hyper_speed:                                 null | string;
    avg_best_speed:                                  null | string;
    distance_hr_avg:                                 number | null;
    sprint_speed:                                    null | string;
    pop_2b:                                          null;
    arm_cs_2b:                                       null;
    strike_rate:                                     null;
    outs_above_average:                              number | null;
    jump_v_avg:                                      null | string;
    max_arm_strength:                                null | string;
    arm_overall:                                     null | string;
    xhr:                                             number | null;
    swing_take_run_value:                            number | null;
    blocks_above_average:                            number | null;
    cs_above_average:                                null;
    fastball_velo:                                   null | string;
    fastball_spin:                                   number | null;
    fastball_extension:                              null | string;
    curveball_spin:                                  number | null;
    pitch_run_value_fastball:                        number;
    pitch_run_value_breaking:                        number;
    pitch_run_value_offspeed:                        number;
    group_fastball_velo:                             string;
    group_breaking_velo:                             string;
    group_offspeed_velo:                             string;
    pitch_usage_fastball:                            number;
    pitch_usage_breaking:                            number;
    pitch_usage_offspeed:                            number;
    fielding_run_value:                              number | null;
    runner_run_value:                                number | null;
    fielding_run_value_arm:                          number | null;
    fielding_run_value_framing:                      null;
    runner_runs_sb:                                  number | null;
    runner_runs_xb:                                  number | null;
    net_bases_runner:                                number | null;
    net_bases_pitcher:                               number | null;
    fast_swing_rate:                                 number | null;
    squared_up_contact:                              number | null;
    squared_up_swing:                                number | null;
    blasts_contact:                                  number | null;
    blasts_swing:                                    number | null;
    swords:                                          number | null;
    avg_swing_speed:                                 null | string;
    avg_swing_length:                                null | string;
    attack_angle:                                    number | null;
    vertical_swing_path:                             number | null;
    acceleration:                                    number | null;
    horizontal_swing_path:                           number | null;
    attack_direction:                                number | null;
    ideal_angle_rate:                                number | null;
    n_squared_up:                                    number | null;
    n_blasts:                                        number | null;
    arm_angle:                                       number | null;
    is_qualified:                                    number | null;
    percent_rank_barrel_unrounded:                   number | null;
    percent_rank_barrel_batted_rate_unrounded:       number | null;
    percent_rank_exit_velocity_avg_unrounded:        number | null;
    percent_rank_exit_velocity_max_unrounded:        number | null;
    percent_rank_launch_angle_avg_unrounded:         number | null;
    percent_rank_xba_unrounded:                      number | null;
    percent_rank_xslg_unrounded:                     number | null;
    percent_rank_xwoba_unrounded:                    number | null;
    percent_rank_woba_unrounded:                     number | null;
    percent_rank_hard_hit_percent_unrounded:         number | null;
    percent_rank_xwobacon_unrounded:                 number | null;
    percent_rank_wobacon_unrounded:                  number | null;
    percent_rank_k_percent_unrounded:                number | null;
    percent_rank_bb_percent_unrounded:               number | null;
    percent_rank_sz_judge_unrounded:                 number | null;
    percent_rank_whiff_percent_unrounded:            number | null;
    percent_rank_chase_percent_unrounded:            number | null;
    percent_rank_ba_unrounded:                       number | null;
    percent_rank_bacon_unrounded:                    number | null;
    percent_rank_xbacon_unrounded:                   number | null;
    percent_rank_babip_unrounded:                    number | null;
    percent_rank_obp_unrounded:                      number | null;
    percent_rank_slg_unrounded:                      number | null;
    percent_rank_xobp_unrounded:                     number | null;
    percent_rank_iso_unrounded:                      number | null;
    percent_rank_xiso_unrounded:                     number | null;
    percent_rank_sweet_spot_percent_unrounded:       number | null;
    percent_rank_distance_hr_avg_unrounded:          number | null;
    percent_rank_groundballs_percent_unrounded:      number | null;
    percent_rank_airballs_percent_unrounded:         number | null;
    percent_rank_pull_percent_airballs_unrounded:    number | null;
    percent_rank_avg_hyper_speed_unrounded:          number | null;
    percent_rank_avg_best_speed_unrounded:           number | null;
    percent_rank_pitch_run_value_fastball_unrounded: number | null;
    percent_rank_pitch_run_value_breaking_unrounded: number | null;
    percent_rank_pitch_run_value_offspeed_unrounded: number | null;
    percent_rank_barrel:                             number | null;
    percent_rank_barrel_batted_rate:                 number | null;
    percent_rank_exit_velocity_avg:                  number | null;
    percent_rank_exit_velocity_max:                  number | null;
    percent_rank_launch_angle_avg:                   number | null;
    percent_rank_xba:                                number | null;
    percent_rank_xslg:                               number | null;
    percent_rank_xwoba:                              number | null;
    percent_rank_woba:                               number | null;
    percent_rank_hard_hit_percent:                   number | null;
    percent_rank_xwobacon:                           number | null;
    percent_rank_wobacon:                            number | null;
    percent_rank_k_percent:                          number | null;
    percent_rank_bb_percent:                         number | null;
    percent_rank_sz_judge:                           number | null;
    percent_rank_whiff_percent:                      number | null;
    percent_rank_chase_percent:                      number | null;
    percent_rank_ba:                                 number | null;
    percent_rank_bacon:                              number | null;
    percent_rank_xbacon:                             number | null;
    percent_rank_babip:                              number | null;
    percent_rank_obp:                                number | null;
    percent_rank_slg:                                number | null;
    percent_rank_xobp:                               number | null;
    percent_rank_iso:                                number | null;
    percent_rank_xiso:                               number | null;
    percent_rank_sweet_spot_percent:                 number | null;
    percent_rank_distance_hr_avg:                    number | null;
    percent_rank_groundballs_percent:                number | null;
    percent_rank_airballs_percent:                   number | null;
    percent_rank_pull_percent_airballs:              number | null;
    percent_rank_avg_hyper_speed:                    number | null;
    percent_rank_avg_best_speed:                     number | null;
    percent_rank_pitch_run_value_fastball:           number | null;
    percent_rank_pitch_run_value_breaking:           number | null;
    percent_rank_pitch_run_value_offspeed:           number | null;
    percent_speed_order:                             number | null;
    percent_rank_speed_order:                        number | null;
    percent_rank_pop_2b:                             null;
    percent_rank_arm_cs_2b:                          null;
    percent_rank_oaa:                                number | null;
    percent_rank_framing:                            null;
    percent_rank_jump:                               number | null;
    percent_rank_fastball_velo:                      number | null;
    percent_rank_fastball_spin:                      number | null;
    percent_rank_fastball_extension:                 number | null;
    percent_rank_cu_spin:                            number | null;
    percent_rank_xera:                               number | null;
    percent_rank_arm_max:                            number | null;
    percent_rank_arm_overall:                        number | null;
    percent_rank_xhr:                                number | null;
    percent_rank_swing_take_run_value:               number | null;
    percent_rank_blocks_above_average:               number | null;
    percent_rank_cs_above_average:                   null;
    percent_rank_fielding_run_value:                 number | null;
    percent_rank_runner_run_value:                   number | null;
    percent_rank_runner_runs_sb:                     number | null;
    percent_rank_runner_runs_xb:                     number | null;
    percent_rank_fielding_run_value_arm:             number | null;
    percent_rank_fielding_run_value_framing:         null;
    percent_rank_blasts_swing:                       number | null;
    percent_rank_swing_speed:                        number | null;
    percent_rank_swing_length:                       number | null;
    percent_rank_squared_up_swing:                   number | null;
    percent_rank_attack_angle:                       number | null;
    percent_rank_vertical_swing_path:                number | null;
    percent_rank_acceleration:                       number | null;
    percent_rank_ideal_angle_rate:                   number | null;
}

export interface StatcastGameLog {
    game_pk:     string;
    play_id:     string;
    name:        string;
    gd:          Date;
    ab_num:      string;
    event:       string;
    bat_team_id: number;
    fld_team_id: number;
    ev:          null | string;
    la:          null | string;
    dist:        null | string;
    pull:        null | string;
    brl:         number | null;
    xban:        null | string;
    xbad:        null | string;
    hh:          string;
    bip:         string;
    v:           null | string;
    pt:          null | string;
    pn:          null | string;
    ab:          string;
    hit:         string;
    is_1b:       string;
    is_2b:       string;
    is_3b:       string;
    is_hr:       string;
    so:          string;
    bb:          string;
    video?:      string;
}

export interface StatcastHistogram {
    histogram_value:           string;
    pitch_count:               string;
    total_pitches:             string;
    hits:                      null | string;
    bbe:                       null | string;
    swings:                    string;
    hr:                        null | string;
    ev:                        string;
    la:                        string;
    pitch_speed:               string;
    ba:                        null | string;
    xba:                       null | string;
    run_exp:                   string;
    bacon:                     null | string;
    xbacon:                    null | string;
    babip:                     null | string;
    obp:                       null | string;
    slg:                       null | string;
    xobp:                      null | string;
    xslg:                      null | string;
    iso:                       null | string;
    xiso:                      null | string;
    woba:                      null | string;
    xwoba:                     null | string;
    wobacon:                   null | string;
    xwobacon:                  null | string;
    xbadiff:                   null | string;
    xslgdiff:                  null | string;
    woba_diff:                 null | string;
    hard_hit_percent:          null | string;
    pitch_percent:             string;
    pitcher_run_exp:           number;
    batter_run_value_per_100:  number;
    pitcher_run_value_per_100: number;
    color?:                    string;
}

export interface StatcastLeader {
    year:                       string;
    player_id:                  string;
    sprint_speed:               null | string;
    speed_order:                null | string;
    pos_speed_order:            null | string;
    age_speed_order:            null | string;
    age:                        number | null;
    percent_speed_order:        null | string;
    pop_2b_sba_count:           null;
    pop_2b_sba:                 null;
    pop_2b_sb:                  null;
    pop_2b_cs:                  null;
    exchange_2b_sba_count:      null;
    exchange_2b_sba:            null;
    exchange_2b_sb:             null;
    exchange_2b_cs:             null;
    maxeff_arm_2b_sba_count:    null;
    maxeff_arm_2b_sba:          null;
    maxeff_arm_2b_sb:           null;
    maxeff_arm_2b_cs:           null;
    pop_3b_sba_count:           null;
    pop_3b_sba:                 null;
    pop_3b_sb:                  null;
    pop_3b_cs:                  null;
    exchange_3b_sba_count:      null;
    exchange_3b_sba:            null;
    exchange_3b_sb:             null;
    exchange_3b_cs:             null;
    maxeff_arm_3b_sba_count:    null;
    maxeff_arm_3b_sba:          null;
    maxeff_arm_3b_sb:           null;
    maxeff_arm_3b_cs:           null;
    exchange_2b_3b_sba:         null;
    maxeff_arm_2b_3b_sba:       null;
    p_2b_cs:                    null;
    p_3b_cs:                    null;
    p_2b_sb:                    null;
    p_3b_sb:                    null;
    p_2b_cs_per:                null;
    p_3b_cs_per:                null;
    p_2b_sb_per:                null;
    p_3b_sb_per:                null;
    n_outs_above_average:       null | string;
    resp_fielder_catch_rate:    null | string;
    actual_catch_rate:          null | string;
    diff_catch_rate:            null | string;
    n_oaa_slice_back_left:      null | string;
    n_oaa_slice_back_right:     null | string;
    n_oaa_slice_back:           null | string;
    n_oaa_slice_back_all:       null | string;
    n_oaa_slice_in_left:        null | string;
    n_oaa_slice_in_right:       null | string;
    n_oaa_slice_in:             null | string;
    n_oaa_slice_in_all:         null | string;
    percent_rank_pop_2b:        null;
    hp_to_1b:                   null | string;
    n_bolts:                    null | string;
    percent_rank_strike_rate:   null;
    framing_n_called_pitches:   null;
    framing_strike_rate:        null;
    framing_strike_rate_11:     null;
    framing_strike_rate_12:     null;
    framing_strike_rate_13:     null;
    framing_strike_rate_14:     null;
    framing_strike_rate_16:     null;
    framing_strike_rate_17:     null;
    framing_strike_rate_18:     null;
    framing_strike_rate_19:     null;
    framing_runs_extra_strikes: null;
    oaa_2star:                  null | string;
    outs_2star:                 null | string;
    attempts_2star:             null | string;
    outs_per_play:              null | string;
    reaction:                   null | string;
    burst:                      null | string;
    route:                      null | string;
    jump:                       null | string;
    percent_rank_reaction:      null | string;
    percent_rank_burst:         null | string;
    percent_rank_route:         null | string;
    percent_rank_jump:          null | string;
    f_bootup_distance:          null | string;
    percent_rank_oaa:           number | null;
    xera:                       number | null;
    era:                        number | null;
    era_minus_xera_diff:        null | string;
    percent_rank_xera:          number | null;
    playerId:                   string;
    season:                     string;
}

export interface StatcastPitches {
    FS?: Cu[];
    FF?: Cu[];
    ST?: Cu[];
    CU?: Cu[];
    SI?: Cu[];
    FC?: Cu[];
    SL?: Cu[];
    FO?: Cu[];
}

export interface Cu {
    x:         string;
    z:         string;
    vel:       string;
    pt:        string;
    swing:     string;
    ball:      string;
    hit:       number;
    z1:        string;
    z3:        string;
    lhb:       number;
    rhb:       number;
    behind:    number;
    ahead:     number;
    even:      number;
    ts:        number;
    gd:        Date;
    pid:       string;
    sz_top:    string;
    sz_bot:    string;
    showVideo: boolean;
    y:         string;
    pitchType: string;
    pitchName: string;
    videoUrl:  string;
}

export interface Zone {
    pitch_percent:                 string;
    total_pitches:                 string;
    player_id:                     number;
    name:                          string;
    api_gameday_pitchzone_cd:      string;
    pitches:                       string;
    bbe:                           string;
    in_zone:                       string;
    out_zone:                      string;
    edge:                          string;
    barrels:                       string;
    hardhit:                       string;
    hard_hit_bip_percent:          string;
    hard_hit_pitches_percent:      string;
    hard_hit_swings_percent:       string;
    brl_bip_percent:               string;
    brl_pitches_percent:           string;
    brl_swings_percent:            string;
    swing_percent:                 string;
    batter_run_exp:                string;
    batter_run_exp_swing:          string;
    batter_run_exp_take:           string;
    batter_run_exp_contact:        string;
    pitcher_run_exp:               string;
    pitcher_run_exp_swing:         string;
    pitcher_run_exp_take:          string;
    pitcher_run_exp_contact:       string;
    in_zone_swing:                 string;
    out_zone_swing:                string;
    in_zone_swing_miss:            string;
    out_zone_swing_miss:           string;
    lhb:                           string;
    rhb:                           string;
    release_speed:                 string;
    hr:                            string;
    hits:                          string;
    singles:                       string;
    doubles:                       string;
    triples:                       string;
    k:                             string;
    pa:                            string;
    ab:                            string;
    swings:                        string;
    misses:                        string;
    gb_percent:                    string;
    ld_percent:                    string;
    fb_percent:                    string;
    pu_percent:                    string;
    ba:                            string;
    xba:                           string;
    bacon:                         string;
    xbacon:                        string;
    babip:                         string;
    obp:                           string;
    slg:                           string;
    xobp:                          string;
    xslg:                          string;
    iso:                           string;
    xiso:                          string;
    woba:                          string;
    xwoba:                         string;
    wobacon:                       string;
    xwobacon:                      string;
    xbadiff:                       string;
    xslgdiff:                      string;
    wobadiff:                      string;
    bb_percent:                    string;
    k_percent:                     string;
    swing:                         string;
    whiff_percent:                 string;
    avg_ev:                        string;
    avg_la:                        string;
    avg_spin:                      string;
    sweetspot_speed_mph:           number;
    swing_length:                  string;
    xbh:                           string;
    attack_angle_zone:             number;
    attack_direction_pullopp_zone: number;
    swing_path_tilt_zone:          number;
    squared_up_swing:              string;
    squared_up_contact:            string;
}
