import type { IDBPDatabase } from "idb";
import {DISTRIBUTION_METRICS, type StatCache, type StatcastDB} from "./statcast";
import type {ExtendedPercentileProperty, PercentileProperty} from "@/utils/stats";
import {getConfig} from "@/utils/config.ts";
import Papa from "papaparse";
import type {StatcastRow} from "@/utils/data_types/autogenerated-statcast-row.ts";
import {LOADED_CUSTOM_STAT_PROPERTIES} from "@/utils/custom-stats.ts";

export function* seasonDates(season: number): Generator<string> {
    if (season < 2008) {
        return;
    }

    const toIsoDate: (date: Date) => string = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;

    const today = new Date().setHours(0, 0, 0, 0);

    const start = new Date(season, 3 - 1, 15);
    const end = new Date(season, 11 - 1, 15);

    for (let date = new Date(start); date <= end && Number(date) < today; date.setDate(date.getDate() + 1)) {
        yield toIsoDate(date);
    }
}

export function getDistributionData(stat: PercentileProperty, season: number): { mean: number, stdev: number } | undefined {
    const result = DISTRIBUTION_METRICS[`${season}:${stat.value}`];
    if (result === undefined) {
        return undefined;
    } else {
        const [mean, stdev] = result;
        return { mean, stdev };
    }
}

export async function getStatFromDB(stat: ExtendedPercentileProperty, season: number, player: number, db: IDBPDatabase<StatcastDB>): Promise<object | undefined> {
    const cache: StatCache<object> | undefined = await db.get('stats', [season, stat.value]);

    if (cache === undefined) {
        return undefined;
    }

    return cache.byPlayer[String(player)];
}

export async function getDayFromURL(date: string): Promise<string | null> {
    const URL: string = `https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7CPO%7CS%7C=&hfSea=&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=${date}&game_date_lt=${date}&team=&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0&type=details&`;

    const result = await fetch(URL);
    if (!result.ok) {
        return null;
    }

    return result.text();
}

export async function getDayFromDB(date: string, db: IDBPDatabase<StatcastDB>): Promise<Papa.ParseResult<StatcastRow>> {
    return Papa.parse(await db.get('date', date) ?? '', {
        header: true,
        dynamicTyping: true,
    });
}

export async function getFileSizeForSeason(season: number, db: IDBPDatabase<StatcastDB>): Promise<number> {
    const result = await db.get('season', String(season));
    return result?.fileSize ?? 0;
}

export async function getCachedSeasons(db: IDBPDatabase<StatcastDB>): Promise<number[]> {
    return (await db.getAllKeys('season')).map(Number);
}

export async function purgeSeason(season: number, db: IDBPDatabase<StatcastDB>) {
    for (const date of seasonDates(season)) {
        await db.delete('date', date);
    }
    await db.delete('season', String(season));
    for (const stat of LOADED_CUSTOM_STAT_PROPERTIES) {
        await db.delete('stats', [season, stat.value]);
    }
}
